version: "3"

services:
  nginx_gateway_server:
    image: nginx:1.23.2
    network_mode: "host"
    container_name: nginx_gateway_container
    restart: always
    volumes:
      - ./www/:/home/www/
      - ./cert/:/home/cert/
      - ./conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
